name: tazkar
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  intl: any
  material_color_utilities: ^0.11.0
  cupertino_icons: ^1.0.8
  archive: ^4.0.7
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  flutter_decorated_text: ^2.0.2
  flutter_svg: ^2.0.10+1
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  get_it: ^8.0.2
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.2
  dartz: ^0.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  sqflite: ^2.4.2
  meta: ^1.15.0
  auto_size_text: ^3.0.0
  awesome_extensions: ^2.0.26
  equatable: ^2.0.7
  lottie: ^3.2.0
  geolocator: ^13.0.4
  flutter_dotenv: ^5.2.1
  flutter_islamic_icons: ^1.0.2
  animations: ^2.0.11
  flutter_spinkit: ^5.2.1
  collection: ^1.18.0
  flutter_session_jwt: ^1.1.0
  flutter_animate: ^4.5.2
  path: ^1.9.0
  flutter_gen: ^5.11.0
  go_router: ^17.0.1
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  easy_localization: ^3.0.8
  go_transitions: ^0.8.3
  rxdart: ^0.28.0
  permission_handler: ^12.0.1
  crypto: ^3.0.3
  bot_toast: ^4.1.3
  hijri: ^3.0.0
  timezone: ^0.10.1
  table_calendar: ^3.2.0
  share_plus: ^12.0.1
  geocoding: ^4.0.0
  flutter_qiblah: ^3.1.0+1
  flutter_upgrade_version: ^1.1.8
  jiffy: ^6.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  flutter_gen_runner: any
  drift_dev: ^2.30.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/surah/
    - assets/images/icons/
    - assets/database/
    - assets/images/png/
    - assets/fonts/quran_fonts_qfc4/
    - assets/images/core/json/
    - assets/images/core/svg/
    - assets/images/error/
    - assets/images/background/
    - assets/images/prayer_time/icon/
    - assets/translations/
    - assets/images/hijri/

  fonts:
    - family: Numbers
      fonts:
        - asset: assets/fonts/arabicNumberRegular.ttf

    - family: SurahNames
      fonts:
        - asset: assets/fonts/sura_juza_names.ttf



    - family: Hafsv8
      fonts:
        - asset: assets/fonts/Hafs.ttf

    - family: Noor
      fonts:
        - asset: assets/fonts/Noor-Regular.ttf
        - asset: assets/fonts/Noor-Light.ttf
          weight: 400
        - asset: assets/fonts/Noor-Bold.ttf
          weight: 600

    - family: Uthmanic
      fonts:
        - asset: assets/fonts/Uthmanic.ttf

    - family: Neirizi
      fonts:
        - asset: assets/fonts/Neirizi.ttf

    - family: Tajweed
      fonts:
        - asset: assets/fonts/tajweed.ttf

    - family: KSAFont
      fonts:
        - asset: assets/fonts/KSARegular.ttf
        - asset: assets/fonts/KSARegular_B.ttf
          weight: 700



    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

